// DOM Elements
const frog = document.getElementById('frog');
const gameWorld = document.getElementById('game-world');
const gameArea = document.getElementById('game-area');
const jumpBtn = document.getElementById('jump-btn');
const powerBar = document.getElementById('power-bar');
const powerPercent = document.getElementById('power-percent');
const levelDisplay = document.getElementById('level');
const xpDisplay = document.getElementById('xp');
const xpNeededDisplay = document.getElementById('xp-needed');
const bestJumpDisplay = document.getElementById('best-jump');
const bestDisplay = document.getElementById('best-display');
const skinsGrid = document.getElementById('skins-grid');
const resultPopup = document.getElementById('result-popup');
const overlay = document.getElementById('overlay');
const resultDistance = document.getElementById('result-distance');
const resultXp = document.getElementById('result-xp');
const levelUpMsg = document.getElementById('level-up-msg');
const unlockMsg = document.getElementById('unlock-msg');
const continueBtn = document.getElementById('continue-btn');
const sleepOverlay = document.getElementById('sleep-overlay');
const sleepCountdown = document.getElementById('sleep-countdown');
const sleepProgress = document.getElementById('sleep-progress');
const awakeTimerDisplay = document.getElementById('awake-timer');

// Labubu DOM elements
const labubuContainer = document.getElementById('labubu-container');
const labubuReveal = document.getElementById('labubu-reveal');
const labubuRevealTitle = document.getElementById('labubu-reveal-title');
const labubuRevealMonster = document.getElementById('labubu-reveal-monster');
const labubuRevealBonus = document.getElementById('labubu-reveal-bonus');
const labubuHint = document.getElementById('labubu-hint');

// Terrain DOM elements
const terrainContainer = document.getElementById('terrain-container');
const highlightsContainer = document.getElementById('highlights-container');
const distanceLabelsContainer = document.getElementById('distance-labels-container');
const distanceSummary = document.getElementById('distance-summary');
const previewOverlay = document.getElementById('preview-overlay');
const previewBadge = document.getElementById('preview-badge');
const lavaDeathOverlay = document.getElementById('lava-death-overlay');
